# Generated by Django 4.2.9 on 2024-02-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='date_addded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activate',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
